name: Update Family Tree Statistics

on:
  push:
    paths:
      - 'alseyat.js'  # Watch for changes to alseyat.js

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Run update script
      run: |
        npm install
        node update_stats.js

    - name: Commit and push changes
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add statistics.json
        git commit -m "Update statistics"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
