name: Update Family Tree Statistics

on:
  push:
    paths:
      - 'alseyat.js'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Run update script
      run: |
        node update_stats.js
